import React from "react";
import { Modal, Text, Button } from '@nextui-org/react';


export const ContentModal = (props) => {
    return (
        <div>
            <Modal
              scroll
              width="600px"
              aria-labelledby="modal-title"
              aria-describedby="modal-description"
              {...props.bindings}
            >
              <Modal.Header>
                <Text h2 id="modal-title" size={18}>
                  About this tool
                </Text>
              </Modal.Header>

              <Modal.Body>
                <Text h4>What this tool is</Text>
                <Text>It automatically creates personalized, guided meditations. Use it to explore specific thoughts and feelings, for guidance or to bring more intent to your everyday life.</Text>
                <Text>Topics to inspire : "I feel anxious about ... ", "I want to be more grateful about ...", "I realised ... . I want to internalize this realisation.", "Today, I get to do ... . I want to appreciate that with more intent." </Text>
                <Text>Know someone who might like this? Share it with them!</Text>
                <Text>Questions? Ask them: <a href="mailto:benni_leitz@hotmail.com" rel="noopener noreferrer">benni_leitz@hotmail.com</a></Text>
                <Text>The meditation script is genererated by OpenAI's GPT API. The audio is generated by Azure's Text-to-Speech API. Music by Andrewkn. Loading animation by Wan Souza.</Text>
                
                <Text h4>Why I created this tool</Text>
                <Text>I often struggle to self reflect, explore difficult ideas or fight stubborn patterns of thought: My mind is quick to get distracted or to interrupt itself with opposing opinions. I have found that guided meditation can help me here: It allows me to drop inherent resistance, be more receiptive to change and make it easier for me to resist distractions. </Text>
                <Text>Meditation apps are great! But either they focus on core meditation techniques (e.g. around mindfulness or gratitude meditations) or they address very general themes. Naturally, they cannot be specific to the meditators personal thoughts nor should they.</Text>
                <Text>And here technology can lend us a hand: ChatGPT is able to generate surprisingly gentle, visual and specific scripts. And today's Text-to-Speech technology makes the scripts come to life.</Text>
              </Modal.Body>

              <Modal.Footer>
                <Button auto onPress={() => props.setVisible(false)} aria-label="close">
                  Close
                </Button>
              </Modal.Footer>
            </Modal>
        </div>
    )
}
